import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SubscribeForm from "./components/SubscribeForm";
import Header from "./components/Header";        // 👈 thêm import ở đây, cùng nhóm import khác

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Header />                                {/* 👈 đặt ở đây, trong JSX, trước children */}
        {children}
        <footer className="mt-auto border-t p-4">
          <SubscribeForm />
        </footer>
      </body>
    </html>
  );
}